# MacMach Operating System
# Copyright (c) 1992 Carnegie Mellon University
# All Rights Reserved.
#
# MacMach was developed by CMU with support from Apple Computer, Inc.
# Use of this software is constrained by the MacMach End-User license.
#  
######################################################################
# HISTORY
# $Log:	Makefile.mac2,v $
# Revision 2.2  91/09/12  16:36:07  bohman
# 	Created Mach 3.0 version from 2.5 version.
# 	[91/09/11  16:58:31  bohman]
# 
# Revision 2.2  90/09/04  16:36:32  bohman
# 	Created.
# 
######################################################################

######################################################################
#BEGIN	Machine dependent Makefile fragment for the Macintosh II
######################################################################

CC=	cc -m68020
AS=	as -m68020

LD=	ld

MD=	md

KCC=	${CC}
KCPP=	${KCC} -E

VOLATILE=

LDFLAGS=-r -d -N -e _start -X
LIBS= -lmachterm

LDDEPS_PREFIX=
SWAPDEPS_PREFIX=
OBJSDEPS=

INCLUDES= -I$(SOURCE_DIR) -I. ${INCLUDES}

AHEADS=

LDOBJS_PREFIX=locore.o ramdisk0a.o
LDOBJS_SUFFIX=

# Special rule to generate the locore.o from ../mac2/locore.S
LOCORE_DEPS=
LOCORE_HEADS=

locore.o: assym.s ../mac2/locore.S ${LOCORE_HEADS}
	${CC} -DLOCORE -I$(SOURCE_DIR)/machine ${SFLAGS} -c ../mac2/locore.S

ioconf.c:
	echo "/* null ioconf.c for mac2 */" >ioconf.c

macServer.c: ../mach/mac2/macserver.defs
	mig $(INCLUDES) -user /dev/null -header /dev/null \
	-server macServer.c ../mach/mac2/macserver.defs

default_pager_object_create.c: ../mach/default_pager_object.defs
	mig $(INCLUDES) \
	-Ddefault_pager_object_create=default_pager_object_create_EXTERNAL \
	-Ddefault_pager_info=default_pager_info_EXTERNAL \
	-user default_pager_object_create.c \
	-header /dev/null -server /dev/null ../mach/default_pager_object.defs

ramdisk0a.o: ramdisk FRC
	./ramdisk /dev/rramdisk0a | ${AS} -o ramdisk0a.o

ramdisk: ../mac2dev/ramdisk.c
	cc -O ../mac2dev/ramdisk.c -o ramdisk

FRC:

#
#  Compilation rules to generate .o from .c for normal files
#
C_RULE_1A=${KCC} -c -O ${COPTS} -fno-defer-pop 
C_RULE_1B=$*.c
C_RULE_2=
C_RULE_3=
C_RULE_4=

######################################################################
#END	 Machine dependent Makefile fragment for the Macintosh II
######################################################################
