.\"
.\" Mach Operating System
.\" Copyright (c) 1991,1990 Carnegie Mellon University
.\" All Rights Reserved.
.\" 
.\" Permission to use, copy, modify and distribute this software and its
.\" documentation is hereby granted, provided that both the copyright
.\" notice and this permission notice appear in all copies of the
.\" software, derivative works or modified versions, and any portions
.\" thereof, and that both notices appear in supporting documentation.
.\" 
.\" CARNEGIE MELLON ALLOWS FREE USE OF THIS SOFTWARE IN ITS 
.\" CONDITION.  CARNEGIE MELLON DISCLAIMS ANY LIABILITY OF ANY KIND FOR
.\" ANY DAMAGES WHATSOEVER RESULTING FROM THE USE OF THIS SOFTWARE.
.\" 
.\" Carnegie Mellon requests users of this software to return to
.\" 
.\"  Software Distribution Coordinator  or  Software.Distribution@CS.CMU.EDU
.\"  School of Computer Science
.\"  Carnegie Mellon University
.\"  Pittsburgh PA 15213-3890
.\" 
.\" any improvements or extensions that they make and grant Carnegie the
.\" rights to redistribute these changes.
.\"
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.\" HISTORY
.\" $Log: mk_major_vers.3,v $
# Revision 1.1  1996/03/01  14:51:53  sclawson
# Changes to install man pages.
#
.\" Revision 1.1.1.1  1995/05/04  06:56:39  sclawson
.\" New files.
.\"
.\" Revision 2.2  92/11/13  17:32:12  mrt
.\" 	Created.
.\" 
.\" 
.\" 
.\"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
.TH MK_MAJOR_VERSION 3 7/22/92
.CM 4
.SH "NAME"
mk_major_version \- Retuns Mach kernel major version number
.SH "SYNOPSIS"
.sp
.ft B
int mk_major_version ();
.ft R
.sp
.fi
.SH "DESCRIPTION"
.I
mk_major_version 
returns 2 on Mach 2.5 systems and 3 on Mach 3.0 systems

