#!/bin/sh -e

# build_world - feel free to uncomment or comment out lines
#               of this script as needed.

mkdir -p ../obj/powermac
sh makedefs/configure

# Build the OSF MK header files
build MAKEFILE_PASS=FIRST

# Build the OSF MK libraries
build -here mach_services/lib/libcthreads
build -here mach_services/lib/libsa_mach
build -here mach_services/lib/libmach
build -here mach_services/lib/libmach_maxonstack

# Build the file_systems library (for the bootstrap task)
# and then the bootstrap task itself
build -here file_systems
build -here bootstrap

# Build the microkernel
build -here mach_kernel MACH_KERNEL_CONFIG=PRODUCTION

# Jam the bootstrap and microkernel together to make "Mach_Kernel"
makeboot PRODUCTION

# Build	the default pager
build -here default_pager

# Build	the name_server and its libraries
#build -here mach_services/lib/libservice
#build -here mach_services/lib/libnetname
#build -here mach_services/servers/netname

# Build the microkernel performance test suite
#build -here mach_services/cmds/mach_perf
